// *********************************************************************************************************
//      DO NOT EDIT. This file has been generated by the Schemarise ALFA toolset. See
// www.schemarise.com
// *********************************************************************************************************
package schemarise.alfa.runtime.model.diff;

@javax.annotation.Generated("com.schemarise.alfa.generators.exporters.java.JavaExporter")
public interface NamespaceModifications
        extends com.schemarise.alfa.runtime.Record,
                schemarise.alfa.runtime.model.diff.IModification {

    schemarise.alfa.runtime.model.diff.EditType getEditType();

    schemarise.alfa.runtime.model.diff.ChangeCategoryType getChangeCategory();

    java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet> getBeforeSnippet();

    java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet> getAfterSnippet();

    java.util.Optional<java.lang.String> getMessage();

    java.lang.String getNamespaceName();

    // <editor-fold defaultstate="collapsed" desc="Builder support">
    public static NamespaceModificationsBuilder builder() {
        return new schemarise.alfa.runtime.model.diff.NamespaceModifications
                ._NamespaceModificationsBuilderImpl();
    }

    public static NamespaceModificationsBuilder builder(
            com.schemarise.alfa.runtime.IBuilderConfig bc) {
        if (bc.getCustomBuilderFactory().isPresent())
            return bc.getCustomBuilderFactory()
                    .get()
                    .builder(
                            bc,
                            schemarise.alfa.runtime.model.diff.NamespaceModifications
                                    .NamespaceModificationsDescriptor.INSTANCE);
        else
            return new schemarise.alfa.runtime.model.diff.NamespaceModifications
                    ._NamespaceModificationsBuilderImpl(bc);
    }

    public default <B extends com.schemarise.alfa.runtime.Builder> B toBuilder(
            com.schemarise.alfa.runtime.IBuilderConfig bc) {
        return com.schemarise.alfa.runtime.utils.AlfaUtils.toBuilder(bc, this);
    }

    public default <B extends com.schemarise.alfa.runtime.Builder> B toBuilder() {
        return toBuilder(com.schemarise.alfa.runtime.BuilderConfig.getInstance());
    }
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Builder Interface">
    public interface NamespaceModificationsBuilder
            extends com.schemarise.alfa.runtime.Builder,
                    com.schemarise.alfa.runtime.AlfaObject,
                    schemarise.alfa.runtime.model.diff.IModification.IModificationBuilder {
        NamespaceModificationsBuilder setEditType(schemarise.alfa.runtime.model.diff.EditType v);

        schemarise.alfa.runtime.model.diff.EditType getEditType();

        NamespaceModificationsBuilder setChangeCategory(
                schemarise.alfa.runtime.model.diff.ChangeCategoryType v);

        schemarise.alfa.runtime.model.diff.ChangeCategoryType getChangeCategory();

        NamespaceModificationsBuilder setBeforeSnippet(
                java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet> v);

        NamespaceModificationsBuilder setBeforeSnippet(
                schemarise.alfa.runtime.model.diff.Snippet v);

        java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet> getBeforeSnippet();

        NamespaceModificationsBuilder setAfterSnippet(
                java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet> v);

        NamespaceModificationsBuilder setAfterSnippet(schemarise.alfa.runtime.model.diff.Snippet v);

        java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet> getAfterSnippet();

        NamespaceModificationsBuilder setMessage(java.util.Optional<java.lang.String> v);

        NamespaceModificationsBuilder setMessage(java.lang.String v);

        java.util.Optional<java.lang.String> getMessage();

        NamespaceModificationsBuilder setNamespaceName(java.lang.String v);

        java.lang.String getNamespaceName();

        NamespaceModifications build();
    }
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Builder Impl class">
    final class _NamespaceModificationsBuilderImpl extends _NamespaceModifications__Base__
            implements NamespaceModificationsBuilder {
        private final com.schemarise.alfa.runtime.IBuilderConfig __builderConfig;

        private java.util.BitSet __missingFields;

        private _NamespaceModificationsBuilderImpl() {
            this(com.schemarise.alfa.runtime.BuilderConfig.getInstance());
        }

        private _NamespaceModificationsBuilderImpl(com.schemarise.alfa.runtime.IBuilderConfig cc) {
            __builderConfig = cc;
            __missingFields = new java.util.BitSet(6);
            __missingFields.set(0, 6);
            setBeforeSnippet(java.util.Optional.empty());
            setAfterSnippet(java.util.Optional.empty());
            setMessage(java.util.Optional.empty());
        }

        protected com.schemarise.alfa.runtime.IBuilderConfig builderConfig() {
            return __builderConfig;
        }

        public com.schemarise.alfa.runtime.TypeDescriptor descriptor() {
            return schemarise.alfa.runtime.model.diff.NamespaceModifications
                    .NamespaceModificationsDescriptor.INSTANCE;
        }

        public NamespaceModificationsBuilder setEditType(
                schemarise.alfa.runtime.model.diff.EditType v) {
            com.schemarise.alfa.runtime.utils.AlfaUtils.notNull("EditType", v);
            this._editType = v;
            clearMissingFlag(
                    schemarise.alfa.runtime.model.diff.NamespaceModifications
                            .NamespaceModificationsDescriptor.FIELD_ID_EDITTYPE);
            return this;
        }

        public NamespaceModificationsBuilder setChangeCategory(
                schemarise.alfa.runtime.model.diff.ChangeCategoryType v) {
            com.schemarise.alfa.runtime.utils.AlfaUtils.notNull("ChangeCategory", v);
            this._changeCategory = v;
            clearMissingFlag(
                    schemarise.alfa.runtime.model.diff.NamespaceModifications
                            .NamespaceModificationsDescriptor.FIELD_ID_CHANGECATEGORY);
            return this;
        }

        public NamespaceModificationsBuilder setBeforeSnippet(
                java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet> v) {
            com.schemarise.alfa.runtime.utils.AlfaUtils.notNull("BeforeSnippet", v);
            this._beforeSnippet = v;
            clearMissingFlag(
                    schemarise.alfa.runtime.model.diff.NamespaceModifications
                            .NamespaceModificationsDescriptor.FIELD_ID_BEFORESNIPPET);
            return this;
        }

        public NamespaceModificationsBuilder setBeforeSnippet(
                schemarise.alfa.runtime.model.diff.Snippet v) {
            this._beforeSnippet = java.util.Optional.ofNullable(v);
            clearMissingFlag(
                    schemarise.alfa.runtime.model.diff.NamespaceModifications
                            .NamespaceModificationsDescriptor.FIELD_ID_BEFORESNIPPET);
            return this;
        }

        public NamespaceModificationsBuilder setAfterSnippet(
                java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet> v) {
            com.schemarise.alfa.runtime.utils.AlfaUtils.notNull("AfterSnippet", v);
            this._afterSnippet = v;
            clearMissingFlag(
                    schemarise.alfa.runtime.model.diff.NamespaceModifications
                            .NamespaceModificationsDescriptor.FIELD_ID_AFTERSNIPPET);
            return this;
        }

        public NamespaceModificationsBuilder setAfterSnippet(
                schemarise.alfa.runtime.model.diff.Snippet v) {
            this._afterSnippet = java.util.Optional.ofNullable(v);
            clearMissingFlag(
                    schemarise.alfa.runtime.model.diff.NamespaceModifications
                            .NamespaceModificationsDescriptor.FIELD_ID_AFTERSNIPPET);
            return this;
        }

        public NamespaceModificationsBuilder setMessage(java.util.Optional<java.lang.String> v) {
            com.schemarise.alfa.runtime.utils.AlfaUtils.notNull("Message", v);
            this._message = v;
            clearMissingFlag(
                    schemarise.alfa.runtime.model.diff.NamespaceModifications
                            .NamespaceModificationsDescriptor.FIELD_ID_MESSAGE);
            return this;
        }

        public NamespaceModificationsBuilder setMessage(java.lang.String v) {
            this._message = java.util.Optional.ofNullable(v);
            clearMissingFlag(
                    schemarise.alfa.runtime.model.diff.NamespaceModifications
                            .NamespaceModificationsDescriptor.FIELD_ID_MESSAGE);
            return this;
        }

        public NamespaceModificationsBuilder setNamespaceName(java.lang.String v) {
            com.schemarise.alfa.runtime.utils.AlfaUtils.notNull("NamespaceName", v);
            this._namespaceName = v;
            clearMissingFlag(
                    schemarise.alfa.runtime.model.diff.NamespaceModifications
                            .NamespaceModificationsDescriptor.FIELD_ID_NAMESPACENAME);
            return this;
        }

        public void modify(java.lang.String fieldName, java.lang.Object val) {
            switch (fieldName) {
                case "EditType":
                    setEditType((schemarise.alfa.runtime.model.diff.EditType) val);
                    break;
                case "ChangeCategory":
                    setChangeCategory((schemarise.alfa.runtime.model.diff.ChangeCategoryType) val);
                    break;
                case "BeforeSnippet":
                    setBeforeSnippet(
                            (java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet>) val);
                    break;
                case "AfterSnippet":
                    setAfterSnippet(
                            (java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet>) val);
                    break;
                case "Message":
                    setMessage((java.util.Optional<java.lang.String>) val);
                    break;
                case "NamespaceName":
                    setNamespaceName((java.lang.String) val);
                    break;
                default:
                    throw new com.schemarise.alfa.runtime.AlfaRuntimeException(
                            schemarise.alfa.runtime.model.asserts.ConstraintType.UnknownField,
                            "Attempt to set unknown field " + fieldName);
            }
        }

        public NamespaceModifications build() {

            com.schemarise.alfa.runtime.utils.Utils.assertMandatoryFieldsSet(
                    builderConfig(),
                    __missingFields,
                    6,
                    schemarise.alfa.runtime.model.diff.NamespaceModifications
                            .NamespaceModificationsDescriptor.INSTANCE);

            NamespaceModifications obj;

            if (builderConfig().getCustomBuilderFactory().isPresent())
                obj =
                        (NamespaceModifications)
                                builderConfig()
                                        .getCustomBuilderFactory()
                                        .get()
                                        .create(
                                                builderConfig(),
                                                descriptor(),
                                                _editType,
                                                _changeCategory,
                                                _beforeSnippet,
                                                _afterSnippet,
                                                _message,
                                                _namespaceName);
            else
                obj =
                        new schemarise.alfa.runtime.model.diff.NamespaceModifications
                                ._NamespaceModificationsConcrete(
                                _editType,
                                _changeCategory,
                                _beforeSnippet,
                                _afterSnippet,
                                _message,
                                _namespaceName);

            if (builderConfig().shouldValidateOnBuild()) obj.validate(builderConfig());

            return obj;
        }

        private void clearMissingFlag(short flag) {

            __missingFields.clear(flag);
        }

        public java.lang.String toString() {
            return com.schemarise.alfa.runtime.utils.Utils.udtToString(
                    "schemarise.alfa.runtime.model.diff.NamespaceModifications",
                    new java.lang.String[] {
                        "EditType",
                        "ChangeCategory",
                        "BeforeSnippet",
                        "AfterSnippet",
                        "Message",
                        "NamespaceName"
                    },
                    new java.lang.Object[] {
                        _editType,
                        _changeCategory,
                        _beforeSnippet,
                        _afterSnippet,
                        _message,
                        _namespaceName
                    });
        }
    }
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Concrete class">

    final class _NamespaceModificationsConcrete extends _NamespaceModifications__Base__
            implements NamespaceModifications {

        private _NamespaceModificationsConcrete() {
            super();
        }

        private _NamespaceModificationsConcrete(
                schemarise.alfa.runtime.model.diff.EditType _editType,
                schemarise.alfa.runtime.model.diff.ChangeCategoryType _changeCategory,
                java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet> _beforeSnippet,
                java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet> _afterSnippet,
                java.util.Optional<java.lang.String> _message,
                java.lang.String _namespaceName) {
            super(
                    _editType,
                    _changeCategory,
                    _beforeSnippet,
                    _afterSnippet,
                    _message,
                    _namespaceName);
        }
    }

    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Base class">
    abstract class _NamespaceModifications__Base__ {
        public schemarise.alfa.runtime.model.diff.EditType _editType;
        public schemarise.alfa.runtime.model.diff.ChangeCategoryType _changeCategory;
        public java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet> _beforeSnippet;
        public java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet> _afterSnippet;
        public java.util.Optional<java.lang.String> _message;
        public java.lang.String _namespaceName;

        public _NamespaceModifications__Base__() {}

        public _NamespaceModifications__Base__(
                schemarise.alfa.runtime.model.diff.EditType _editType,
                schemarise.alfa.runtime.model.diff.ChangeCategoryType _changeCategory,
                java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet> _beforeSnippet,
                java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet> _afterSnippet,
                java.util.Optional<java.lang.String> _message,
                java.lang.String _namespaceName) {
            this._editType = _editType;
            this._changeCategory = _changeCategory;
            this._beforeSnippet = _beforeSnippet;
            this._afterSnippet = _afterSnippet;
            this._message = _message;
            this._namespaceName = _namespaceName;
        }

        public schemarise.alfa.runtime.model.diff.EditType getEditType() {
            return _editType;
        }

        public schemarise.alfa.runtime.model.diff.ChangeCategoryType getChangeCategory() {
            return _changeCategory;
        }

        public java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet> getBeforeSnippet() {
            return _beforeSnippet;
        }

        public java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet> getAfterSnippet() {
            return _afterSnippet;
        }

        public java.util.Optional<java.lang.String> getMessage() {
            return _message;
        }

        public java.lang.String getNamespaceName() {
            return _namespaceName;
        }

        public int hashCode() {
            return java.util.Objects.hash(
                    _editType,
                    _changeCategory,
                    _beforeSnippet,
                    _afterSnippet,
                    _message,
                    _namespaceName);
        }

        public java.lang.String toString() {
            return com.schemarise.alfa.runtime.utils.Utils.udtToString(
                    "schemarise.alfa.runtime.model.diff.NamespaceModifications",
                    new java.lang.String[] {
                        "EditType",
                        "ChangeCategory",
                        "BeforeSnippet",
                        "AfterSnippet",
                        "Message",
                        "NamespaceName"
                    },
                    new java.lang.Object[] {
                        _editType,
                        _changeCategory,
                        _beforeSnippet,
                        _afterSnippet,
                        _message,
                        _namespaceName
                    });
        }

        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o
                    instanceof
                    schemarise.alfa.runtime.model.diff.NamespaceModifications
                            ._NamespaceModificationsConcrete)) return false;
            schemarise.alfa.runtime.model.diff.NamespaceModifications
                            ._NamespaceModificationsConcrete
                    rhs =
                            (schemarise.alfa.runtime.model.diff.NamespaceModifications
                                            ._NamespaceModificationsConcrete)
                                    o;
            return java.util.Objects.equals(_editType, rhs._editType)
                    && java.util.Objects.equals(_changeCategory, rhs._changeCategory)
                    && java.util.Objects.equals(_beforeSnippet, rhs._beforeSnippet)
                    && java.util.Objects.equals(_afterSnippet, rhs._afterSnippet)
                    && java.util.Objects.equals(_message, rhs._message)
                    && java.util.Objects.equals(_namespaceName, rhs._namespaceName);
        }

        public void traverse(com.schemarise.alfa.runtime.Visitor v) {}

        public java.util.Optional<? extends com.schemarise.alfa.runtime.Key> get$key() {
            return java.util.Optional.empty();
        }

        public com.schemarise.alfa.runtime.TypeDescriptor descriptor() {
            return schemarise.alfa.runtime.model.diff.NamespaceModifications
                    .NamespaceModificationsDescriptor.INSTANCE;
        }

        public Object get(java.lang.String fieldName) {
            switch (fieldName) {
                case "EditType":
                    return _editType;
                case "ChangeCategory":
                    return _changeCategory;
                case "BeforeSnippet":
                    return _beforeSnippet;
                case "AfterSnippet":
                    return _afterSnippet;
                case "Message":
                    return _message;
                case "NamespaceName":
                    return _namespaceName;
                default:
                    throw new com.schemarise.alfa.runtime.AlfaRuntimeException(
                            "Cannot get unknown field " + fieldName);
            }
        }

        public void validate(com.schemarise.alfa.runtime.IBuilderConfig __builderConfig) {
            getEditType().validate(__builderConfig);
            getChangeCategory().validate(__builderConfig);
            if (getBeforeSnippet().isPresent()) {
                getBeforeSnippet().get().validate(__builderConfig);
            }
            if (getAfterSnippet().isPresent()) {
                getAfterSnippet().get().validate(__builderConfig);
            }

            // TODO
            // _key if exists, will be mandatory
        }
    }

    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="TypeDescriptor class">

    public static final class NamespaceModificationsDescriptor
            extends com.schemarise.alfa.runtime.utils.DefaultTypeDescriptor {
        public static java.lang.String TYPE_NAME =
                "schemarise.alfa.runtime.model.diff.NamespaceModifications";
        public static schemarise.alfa.runtime.model.diff.NamespaceModifications
                        .NamespaceModificationsDescriptor
                INSTANCE =
                        new schemarise.alfa.runtime.model.diff.NamespaceModifications
                                .NamespaceModificationsDescriptor();

        private schemarise.alfa.runtime.model.UdtDataType _asUdtType_ =
                schemarise.alfa.runtime.model.UdtDataType.builder()
                        .setUdtType(schemarise.alfa.runtime.model.UdtMetaType.recordType)
                        .setFullyQualifiedName(TYPE_NAME)
                        .build();
        public static final short FIELD_ID_EDITTYPE = 0;
        public static final String FIELD_EDITTYPE = "EditType";

        public static final short FIELD_ID_CHANGECATEGORY = 1;
        public static final String FIELD_CHANGECATEGORY = "ChangeCategory";

        public static final short FIELD_ID_BEFORESNIPPET = 2;
        public static final String FIELD_BEFORESNIPPET = "BeforeSnippet";

        public static final short FIELD_ID_AFTERSNIPPET = 3;
        public static final String FIELD_AFTERSNIPPET = "AfterSnippet";

        public static final short FIELD_ID_MESSAGE = 4;
        public static final String FIELD_MESSAGE = "Message";

        public static final short FIELD_ID_NAMESPACENAME = 5;
        public static final String FIELD_NAMESPACENAME = "NamespaceName";

        private schemarise.alfa.runtime.model.UdtDataType _editTypeType =
                schemarise.alfa.runtime.model.UdtDataType.builder()
                        .setFullyQualifiedName("schemarise.alfa.runtime.model.diff.EditType")
                        .setUdtType(schemarise.alfa.runtime.model.UdtMetaType.enumType)
                        .build();

        private schemarise.alfa.runtime.model.UdtDataType _changeCategoryType =
                schemarise.alfa.runtime.model.UdtDataType.builder()
                        .setFullyQualifiedName(
                                "schemarise.alfa.runtime.model.diff.ChangeCategoryType")
                        .setUdtType(schemarise.alfa.runtime.model.UdtMetaType.enumType)
                        .build();

        private schemarise.alfa.runtime.model.OptionalDataType _beforeSnippetType =
                schemarise.alfa.runtime.model.OptionalDataType.builder()
                        .setComponentType(
                                schemarise.alfa.runtime.model.UdtDataType.builder()
                                        .setFullyQualifiedName(
                                                "schemarise.alfa.runtime.model.diff.Snippet")
                                        .setUdtType(
                                                schemarise.alfa.runtime.model.UdtMetaType
                                                        .recordType)
                                        .build())
                        .build();

        private schemarise.alfa.runtime.model.OptionalDataType _afterSnippetType =
                schemarise.alfa.runtime.model.OptionalDataType.builder()
                        .setComponentType(
                                schemarise.alfa.runtime.model.UdtDataType.builder()
                                        .setFullyQualifiedName(
                                                "schemarise.alfa.runtime.model.diff.Snippet")
                                        .setUdtType(
                                                schemarise.alfa.runtime.model.UdtMetaType
                                                        .recordType)
                                        .build())
                        .build();

        private schemarise.alfa.runtime.model.OptionalDataType _messageType =
                schemarise.alfa.runtime.model.OptionalDataType.builder()
                        .setComponentType(
                                schemarise.alfa.runtime.model.ScalarDataType.builder()
                                        .setScalarType(
                                                schemarise.alfa.runtime.model.ScalarType.stringType)
                                        .build())
                        .build();

        private schemarise.alfa.runtime.model.ScalarDataType _namespaceNameType =
                schemarise.alfa.runtime.model.ScalarDataType.builder()
                        .setScalarType(schemarise.alfa.runtime.model.ScalarType.stringType)
                        .build();

        /* -- Consumer schemarise.alfa.runtime.model.diff.EditType -- */
        java.util.function.Function<
                        com.schemarise.alfa.runtime.DataSupplier,
                        schemarise.alfa.runtime.model.diff.EditType>
                _editTypeConsumerInner1 =
                        (supplierInner1) -> {
                            return supplierInner1.objectValue(
                                    ((schemarise.alfa.runtime.model.UdtDataType) _editTypeType));
                        };
        java.util.function.BiConsumer<
                        schemarise.alfa.runtime.model.diff.NamespaceModifications
                                ._NamespaceModificationsBuilderImpl,
                        com.schemarise.alfa.runtime.DataSupplier>
                _editTypeConsumer =
                        (builder, supplier) -> {
                            builder.setEditType(_editTypeConsumerInner1.apply(supplier));
                        };
        /* -- Consumer schemarise.alfa.runtime.model.diff.ChangeCategoryType -- */
        java.util.function.Function<
                        com.schemarise.alfa.runtime.DataSupplier,
                        schemarise.alfa.runtime.model.diff.ChangeCategoryType>
                _changeCategoryConsumerInner1 =
                        (supplierInner1) -> {
                            return supplierInner1.objectValue(
                                    ((schemarise.alfa.runtime.model.UdtDataType)
                                            _changeCategoryType));
                        };
        java.util.function.BiConsumer<
                        schemarise.alfa.runtime.model.diff.NamespaceModifications
                                ._NamespaceModificationsBuilderImpl,
                        com.schemarise.alfa.runtime.DataSupplier>
                _changeCategoryConsumer =
                        (builder, supplier) -> {
                            builder.setChangeCategory(
                                    _changeCategoryConsumerInner1.apply(supplier));
                        };
        /* -- Consumer schemarise.alfa.runtime.model.diff.Snippet ? -- */
        java.util.function.Function<
                        com.schemarise.alfa.runtime.DataSupplier,
                        java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet>>
                _beforeSnippetConsumerInner1 =
                        (supplierInner1) -> {
                            java.util.function.Function<
                                            com.schemarise.alfa.runtime.DataSupplier,
                                            schemarise.alfa.runtime.model.diff.Snippet>
                                    _beforeSnippetConsumerInner2 =
                                            (supplierInner2) -> {
                                                return supplierInner2.objectValue(
                                                        ((schemarise.alfa.runtime.model.UdtDataType)
                                                                ((schemarise.alfa.runtime.model
                                                                                        .OptionalDataType)
                                                                                _beforeSnippetType)
                                                                        .getComponentType()));
                                            };
                            return supplierInner1.optionalValue(
                                    ((schemarise.alfa.runtime.model.OptionalDataType)
                                            _beforeSnippetType),
                                    _beforeSnippetConsumerInner2);
                        };
        java.util.function.BiConsumer<
                        schemarise.alfa.runtime.model.diff.NamespaceModifications
                                ._NamespaceModificationsBuilderImpl,
                        com.schemarise.alfa.runtime.DataSupplier>
                _beforeSnippetConsumer =
                        (builder, supplier) -> {
                            builder.setBeforeSnippet(_beforeSnippetConsumerInner1.apply(supplier));
                        };
        /* -- Consumer schemarise.alfa.runtime.model.diff.Snippet ? -- */
        java.util.function.Function<
                        com.schemarise.alfa.runtime.DataSupplier,
                        java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet>>
                _afterSnippetConsumerInner1 =
                        (supplierInner1) -> {
                            java.util.function.Function<
                                            com.schemarise.alfa.runtime.DataSupplier,
                                            schemarise.alfa.runtime.model.diff.Snippet>
                                    _afterSnippetConsumerInner2 =
                                            (supplierInner2) -> {
                                                return supplierInner2.objectValue(
                                                        ((schemarise.alfa.runtime.model.UdtDataType)
                                                                ((schemarise.alfa.runtime.model
                                                                                        .OptionalDataType)
                                                                                _afterSnippetType)
                                                                        .getComponentType()));
                                            };
                            return supplierInner1.optionalValue(
                                    ((schemarise.alfa.runtime.model.OptionalDataType)
                                            _afterSnippetType),
                                    _afterSnippetConsumerInner2);
                        };
        java.util.function.BiConsumer<
                        schemarise.alfa.runtime.model.diff.NamespaceModifications
                                ._NamespaceModificationsBuilderImpl,
                        com.schemarise.alfa.runtime.DataSupplier>
                _afterSnippetConsumer =
                        (builder, supplier) -> {
                            builder.setAfterSnippet(_afterSnippetConsumerInner1.apply(supplier));
                        };
        /* -- Consumer string ? -- */
        java.util.function.Function<
                        com.schemarise.alfa.runtime.DataSupplier,
                        java.util.Optional<java.lang.String>>
                _messageConsumerInner1 =
                        (supplierInner1) -> {
                            java.util.function.Function<
                                            com.schemarise.alfa.runtime.DataSupplier,
                                            java.lang.String>
                                    _messageConsumerInner2 =
                                            (supplierInner2) -> {
                                                return supplierInner2.stringValue(
                                                        ((schemarise.alfa.runtime.model
                                                                        .ScalarDataType)
                                                                ((schemarise.alfa.runtime.model
                                                                                        .OptionalDataType)
                                                                                _messageType)
                                                                        .getComponentType()));
                                            };
                            return supplierInner1.optionalValue(
                                    ((schemarise.alfa.runtime.model.OptionalDataType) _messageType),
                                    _messageConsumerInner2);
                        };
        java.util.function.BiConsumer<
                        schemarise.alfa.runtime.model.diff.NamespaceModifications
                                ._NamespaceModificationsBuilderImpl,
                        com.schemarise.alfa.runtime.DataSupplier>
                _messageConsumer =
                        (builder, supplier) -> {
                            builder.setMessage(_messageConsumerInner1.apply(supplier));
                        };
        /* -- Consumer string -- */
        java.util.function.Function<com.schemarise.alfa.runtime.DataSupplier, java.lang.String>
                _namespaceNameConsumerInner1 =
                        (supplierInner1) -> {
                            return supplierInner1.stringValue(
                                    ((schemarise.alfa.runtime.model.ScalarDataType)
                                            _namespaceNameType));
                        };
        java.util.function.BiConsumer<
                        schemarise.alfa.runtime.model.diff.NamespaceModifications
                                ._NamespaceModificationsBuilderImpl,
                        com.schemarise.alfa.runtime.DataSupplier>
                _namespaceNameConsumer =
                        (builder, supplier) -> {
                            builder.setNamespaceName(_namespaceNameConsumerInner1.apply(supplier));
                        };

        /* -- Supplier schemarise.alfa.runtime.model.diff.EditType -- */
        java.util.function.BiConsumer<
                        schemarise.alfa.runtime.model.diff.EditType,
                        com.schemarise.alfa.runtime.DataConsumer>
                _editTypeSupplierInner1 =
                        (pInner1, consumerInner1) -> {
                            consumerInner1.consume(
                                    ((schemarise.alfa.runtime.model.UdtDataType) _editTypeType),
                                    pInner1);
                        };
        private java.util.function.BiConsumer<
                        schemarise.alfa.runtime.model.diff.NamespaceModifications,
                        com.schemarise.alfa.runtime.DataConsumer>
                _editTypeSupplier =
                        (p, consumer) -> {
                            _editTypeSupplierInner1.accept(p.getEditType(), consumer);
                        };
        /* -- Supplier schemarise.alfa.runtime.model.diff.ChangeCategoryType -- */
        java.util.function.BiConsumer<
                        schemarise.alfa.runtime.model.diff.ChangeCategoryType,
                        com.schemarise.alfa.runtime.DataConsumer>
                _changeCategorySupplierInner1 =
                        (pInner1, consumerInner1) -> {
                            consumerInner1.consume(
                                    ((schemarise.alfa.runtime.model.UdtDataType)
                                            _changeCategoryType),
                                    pInner1);
                        };
        private java.util.function.BiConsumer<
                        schemarise.alfa.runtime.model.diff.NamespaceModifications,
                        com.schemarise.alfa.runtime.DataConsumer>
                _changeCategorySupplier =
                        (p, consumer) -> {
                            _changeCategorySupplierInner1.accept(p.getChangeCategory(), consumer);
                        };
        /* -- Supplier schemarise.alfa.runtime.model.diff.Snippet ? -- */
        java.util.function.BiConsumer<
                        java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet>,
                        com.schemarise.alfa.runtime.DataConsumer>
                _beforeSnippetSupplierInner1 =
                        (pInner1, consumerInner1) -> {
                            java.util.function.BiConsumer<
                                            schemarise.alfa.runtime.model.diff.Snippet,
                                            com.schemarise.alfa.runtime.DataConsumer>
                                    _beforeSnippetSupplierInner2 =
                                            (pInner2, consumerInner2) -> {
                                                consumerInner2.consume(
                                                        ((schemarise.alfa.runtime.model.UdtDataType)
                                                                ((schemarise.alfa.runtime.model
                                                                                        .OptionalDataType)
                                                                                _beforeSnippetType)
                                                                        .getComponentType()),
                                                        pInner2);
                                            };
                            consumerInner1.consume(
                                    ((schemarise.alfa.runtime.model.OptionalDataType)
                                            _beforeSnippetType),
                                    pInner1,
                                    _beforeSnippetSupplierInner2);
                        };
        private java.util.function.BiConsumer<
                        schemarise.alfa.runtime.model.diff.NamespaceModifications,
                        com.schemarise.alfa.runtime.DataConsumer>
                _beforeSnippetSupplier =
                        (p, consumer) -> {
                            _beforeSnippetSupplierInner1.accept(p.getBeforeSnippet(), consumer);
                        };
        /* -- Supplier schemarise.alfa.runtime.model.diff.Snippet ? -- */
        java.util.function.BiConsumer<
                        java.util.Optional<schemarise.alfa.runtime.model.diff.Snippet>,
                        com.schemarise.alfa.runtime.DataConsumer>
                _afterSnippetSupplierInner1 =
                        (pInner1, consumerInner1) -> {
                            java.util.function.BiConsumer<
                                            schemarise.alfa.runtime.model.diff.Snippet,
                                            com.schemarise.alfa.runtime.DataConsumer>
                                    _afterSnippetSupplierInner2 =
                                            (pInner2, consumerInner2) -> {
                                                consumerInner2.consume(
                                                        ((schemarise.alfa.runtime.model.UdtDataType)
                                                                ((schemarise.alfa.runtime.model
                                                                                        .OptionalDataType)
                                                                                _afterSnippetType)
                                                                        .getComponentType()),
                                                        pInner2);
                                            };
                            consumerInner1.consume(
                                    ((schemarise.alfa.runtime.model.OptionalDataType)
                                            _afterSnippetType),
                                    pInner1,
                                    _afterSnippetSupplierInner2);
                        };
        private java.util.function.BiConsumer<
                        schemarise.alfa.runtime.model.diff.NamespaceModifications,
                        com.schemarise.alfa.runtime.DataConsumer>
                _afterSnippetSupplier =
                        (p, consumer) -> {
                            _afterSnippetSupplierInner1.accept(p.getAfterSnippet(), consumer);
                        };
        /* -- Supplier string ? -- */
        java.util.function.BiConsumer<
                        java.util.Optional<java.lang.String>,
                        com.schemarise.alfa.runtime.DataConsumer>
                _messageSupplierInner1 =
                        (pInner1, consumerInner1) -> {
                            java.util.function.BiConsumer<
                                            java.lang.String,
                                            com.schemarise.alfa.runtime.DataConsumer>
                                    _messageSupplierInner2 =
                                            (pInner2, consumerInner2) -> {
                                                consumerInner2.consume(
                                                        ((schemarise.alfa.runtime.model
                                                                        .ScalarDataType)
                                                                ((schemarise.alfa.runtime.model
                                                                                        .OptionalDataType)
                                                                                _messageType)
                                                                        .getComponentType()),
                                                        pInner2);
                                            };
                            consumerInner1.consume(
                                    ((schemarise.alfa.runtime.model.OptionalDataType) _messageType),
                                    pInner1,
                                    _messageSupplierInner2);
                        };
        private java.util.function.BiConsumer<
                        schemarise.alfa.runtime.model.diff.NamespaceModifications,
                        com.schemarise.alfa.runtime.DataConsumer>
                _messageSupplier =
                        (p, consumer) -> {
                            _messageSupplierInner1.accept(p.getMessage(), consumer);
                        };
        /* -- Supplier string -- */
        java.util.function.BiConsumer<java.lang.String, com.schemarise.alfa.runtime.DataConsumer>
                _namespaceNameSupplierInner1 =
                        (pInner1, consumerInner1) -> {
                            consumerInner1.consume(
                                    ((schemarise.alfa.runtime.model.ScalarDataType)
                                            _namespaceNameType),
                                    pInner1);
                        };
        private java.util.function.BiConsumer<
                        schemarise.alfa.runtime.model.diff.NamespaceModifications,
                        com.schemarise.alfa.runtime.DataConsumer>
                _namespaceNameSupplier =
                        (p, consumer) -> {
                            _namespaceNameSupplierInner1.accept(p.getNamespaceName(), consumer);
                        };

        public java.util.Optional<
                        java.util.function.BiConsumer<
                                NamespaceModifications, com.schemarise.alfa.runtime.DataConsumer>>
                getFieldSupplier(java.lang.String fieldName) {
            return _fieldsMeta_.get(fieldName).getSupplier();
        }

        public java.util.Optional<
                        java.util.function.BiConsumer<
                                com.schemarise.alfa.runtime.Builder,
                                com.schemarise.alfa.runtime.DataSupplier>>
                getFieldConsumer(java.lang.String fieldName) {
            return _fieldsMeta_.get(fieldName).getConsumer();
        }

        public com.schemarise.alfa.runtime.FieldMeta editTypeMeta =
                new com.schemarise.alfa.runtime.FieldMeta(
                        java.util.Optional.of(_editTypeSupplier),
                        java.util.Optional.of(_editTypeConsumer),
                        java.util.Optional.of(_editTypeSupplierInner1),
                        java.util.Optional.of(_editTypeConsumerInner1),
                        _editTypeType,
                        FIELD_EDITTYPE,
                        java.util.Optional.empty());
        public com.schemarise.alfa.runtime.FieldMeta changeCategoryMeta =
                new com.schemarise.alfa.runtime.FieldMeta(
                        java.util.Optional.of(_changeCategorySupplier),
                        java.util.Optional.of(_changeCategoryConsumer),
                        java.util.Optional.of(_changeCategorySupplierInner1),
                        java.util.Optional.of(_changeCategoryConsumerInner1),
                        _changeCategoryType,
                        FIELD_CHANGECATEGORY,
                        java.util.Optional.empty());
        public com.schemarise.alfa.runtime.FieldMeta beforeSnippetMeta =
                new com.schemarise.alfa.runtime.FieldMeta(
                        java.util.Optional.of(_beforeSnippetSupplier),
                        java.util.Optional.of(_beforeSnippetConsumer),
                        java.util.Optional.of(_beforeSnippetSupplierInner1),
                        java.util.Optional.of(_beforeSnippetConsumerInner1),
                        _beforeSnippetType,
                        FIELD_BEFORESNIPPET,
                        java.util.Optional.empty());
        public com.schemarise.alfa.runtime.FieldMeta afterSnippetMeta =
                new com.schemarise.alfa.runtime.FieldMeta(
                        java.util.Optional.of(_afterSnippetSupplier),
                        java.util.Optional.of(_afterSnippetConsumer),
                        java.util.Optional.of(_afterSnippetSupplierInner1),
                        java.util.Optional.of(_afterSnippetConsumerInner1),
                        _afterSnippetType,
                        FIELD_AFTERSNIPPET,
                        java.util.Optional.empty());
        public com.schemarise.alfa.runtime.FieldMeta messageMeta =
                new com.schemarise.alfa.runtime.FieldMeta(
                        java.util.Optional.of(_messageSupplier),
                        java.util.Optional.of(_messageConsumer),
                        java.util.Optional.of(_messageSupplierInner1),
                        java.util.Optional.of(_messageConsumerInner1),
                        _messageType,
                        FIELD_MESSAGE,
                        java.util.Optional.empty());
        public com.schemarise.alfa.runtime.FieldMeta namespaceNameMeta =
                new com.schemarise.alfa.runtime.FieldMeta(
                        java.util.Optional.of(_namespaceNameSupplier),
                        java.util.Optional.of(_namespaceNameConsumer),
                        java.util.Optional.of(_namespaceNameSupplierInner1),
                        java.util.Optional.of(_namespaceNameConsumerInner1),
                        _namespaceNameType,
                        FIELD_NAMESPACENAME,
                        java.util.Optional.empty());

        @Override
        public boolean hasBuilder() {
            return true;
        }

        @Override
        public boolean convertableToBuilder() {
            return true;
        }

        @Override
        public NamespaceModificationsBuilder builder() {
            return new schemarise.alfa.runtime.model.diff.NamespaceModifications
                    ._NamespaceModificationsBuilderImpl();
        }

        @Override
        public NamespaceModificationsBuilder builder(
                com.schemarise.alfa.runtime.IBuilderConfig cc) {
            return new schemarise.alfa.runtime.model.diff.NamespaceModifications
                    ._NamespaceModificationsBuilderImpl(cc);
        }

        public NamespaceModificationsDescriptor() {
            super.init();
        }

        protected java.util.Map<java.lang.String, schemarise.alfa.runtime.model.Assert> _asserts_ =
                java.util.Collections.unmodifiableMap(
                        new java.util.LinkedHashMap() {
                            {
                            }
                        });

        protected java.util.Map<
                        java.lang.String,
                        com.schemarise.alfa.runtime.FieldMeta<NamespaceModifications>>
                _fieldsMeta_ =
                        java.util.Collections.unmodifiableMap(
                                new java.util.LinkedHashMap() {
                                    {
                                        put(FIELD_EDITTYPE, editTypeMeta);
                                        put(FIELD_CHANGECATEGORY, changeCategoryMeta);
                                        put(FIELD_BEFORESNIPPET, beforeSnippetMeta);
                                        put(FIELD_AFTERSNIPPET, afterSnippetMeta);
                                        put(FIELD_MESSAGE, messageMeta);
                                        put(FIELD_NAMESPACENAME, namespaceNameMeta);
                                    }
                                });

        @Override
        public schemarise.alfa.runtime.model.UdtDataType getUdtDataType() {
            return _asUdtType_;
        }

        @Override
        public java.util.Map<java.lang.String, schemarise.alfa.runtime.model.Assert> getAsserts() {
            return _asserts_;
        }

        @Override
        public java.util.Map<
                        java.lang.String,
                        com.schemarise.alfa.runtime.FieldMeta<NamespaceModifications>>
                getAllFieldsMeta() {
            return _fieldsMeta_;
        }

        @Override
        /** Not applicable - this is not an entity or a key directly linked to an entity */
        public java.util.Optional<com.schemarise.alfa.runtime.TypeDescriptor> getEntityKeyModel() {
            return java.util.Optional.empty();
        }

        @Override
        public java.lang.String fieldIdName(int id) {
            switch (id) {
                case FIELD_ID_EDITTYPE:
                    return FIELD_EDITTYPE;
                case FIELD_ID_CHANGECATEGORY:
                    return FIELD_CHANGECATEGORY;
                case FIELD_ID_BEFORESNIPPET:
                    return FIELD_BEFORESNIPPET;
                case FIELD_ID_AFTERSNIPPET:
                    return FIELD_AFTERSNIPPET;
                case FIELD_ID_MESSAGE:
                    return FIELD_MESSAGE;
                case FIELD_ID_NAMESPACENAME:
                    return FIELD_NAMESPACENAME;
                default:
                    throw new com.schemarise.alfa.runtime.AlfaRuntimeException(
                            "Unknown field id " + id);
            }
        }

        public boolean hasAbstractTypeFieldsInClosure() {
            return true;
        }

        public java.util.Set<java.lang.String> getImmediateDescendants() {
            return java.util.Collections.emptySet();
        }

        public java.util.Optional<
                        java.util.Map<java.lang.String, schemarise.alfa.runtime.model.Expression>>
                getAnnotations() {
            return java.util.Optional.empty();
        }

        public java.util.Set<schemarise.alfa.runtime.model.ModifierType> getModifiers() {
            return new java.util.HashSet<schemarise.alfa.runtime.model.ModifierType>() {
                {
                }
            };
        }

        public java.lang.String getChecksum() {
            /*
            schemarise.alfa.runtime.model.diff.NamespaceModifications{AfterSnippet:optional<schemarise.alfa.runtime.model.diff.Snippet[505d47e0];>;BeforeSnippet:optional<schemarise.alfa.runtime.model.diff.Snippet[505d47e0];>;ChangeCategory:schemarise.alfa.runtime.model.diff.ChangeCategoryType[de6e8578];EditType:schemarise.alfa.runtime.model.diff.EditType[25750a26];Message:optional<string;>;NamespaceName:string;}
            schemarise.alfa.runtime.model.diff.NamespaceModifications{ChangeCategory:schemarise.alfa.runtime.model.diff.ChangeCategoryType[de6e8578];EditType:schemarise.alfa.runtime.model.diff.EditType[25750a26];NamespaceName:string;}
            */
            return "c8f02b98:679fe9d3";
        }
    }
    // </editor-fold>

}
