// *********************************************************************************************************
//      DO NOT EDIT. This file has been generated by the Schemarise ALFA toolset. See
// www.schemarise.com
// *********************************************************************************************************
package schemarise.alfa.runtime.model.diff;

@javax.annotation.Generated("com.schemarise.alfa.generators.exporters.java.JavaExporter")
public interface Snippet extends com.schemarise.alfa.runtime.Record {

    java.lang.String getCode();

    // <editor-fold defaultstate="collapsed" desc="Builder support">
    public static SnippetBuilder builder() {
        return new schemarise.alfa.runtime.model.diff.Snippet._SnippetBuilderImpl();
    }

    public static SnippetBuilder builder(com.schemarise.alfa.runtime.IBuilderConfig bc) {
        if (bc.getCustomBuilderFactory().isPresent())
            return bc.getCustomBuilderFactory()
                    .get()
                    .builder(
                            bc,
                            schemarise.alfa.runtime.model.diff.Snippet.SnippetDescriptor.INSTANCE);
        else return new schemarise.alfa.runtime.model.diff.Snippet._SnippetBuilderImpl(bc);
    }

    public default <B extends com.schemarise.alfa.runtime.Builder> B toBuilder(
            com.schemarise.alfa.runtime.IBuilderConfig bc) {
        return com.schemarise.alfa.runtime.utils.AlfaUtils.toBuilder(bc, this);
    }

    public default <B extends com.schemarise.alfa.runtime.Builder> B toBuilder() {
        return toBuilder(com.schemarise.alfa.runtime.BuilderConfig.getInstance());
    }
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Builder Interface">
    public interface SnippetBuilder
            extends com.schemarise.alfa.runtime.Builder, com.schemarise.alfa.runtime.AlfaObject {
        SnippetBuilder setCode(java.lang.String v);

        java.lang.String getCode();

        Snippet build();
    }
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Builder Impl class">
    final class _SnippetBuilderImpl extends _Snippet__Base__ implements SnippetBuilder {
        private final com.schemarise.alfa.runtime.IBuilderConfig __builderConfig;

        private java.util.BitSet __missingFields;

        private _SnippetBuilderImpl() {
            this(com.schemarise.alfa.runtime.BuilderConfig.getInstance());
        }

        private _SnippetBuilderImpl(com.schemarise.alfa.runtime.IBuilderConfig cc) {
            __builderConfig = cc;
            __missingFields = new java.util.BitSet(1);
            __missingFields.set(0, 1);
        }

        protected com.schemarise.alfa.runtime.IBuilderConfig builderConfig() {
            return __builderConfig;
        }

        public com.schemarise.alfa.runtime.TypeDescriptor descriptor() {
            return schemarise.alfa.runtime.model.diff.Snippet.SnippetDescriptor.INSTANCE;
        }

        public SnippetBuilder setCode(java.lang.String v) {
            com.schemarise.alfa.runtime.utils.AlfaUtils.notNull("Code", v);
            this._code = v;
            clearMissingFlag(
                    schemarise.alfa.runtime.model.diff.Snippet.SnippetDescriptor.FIELD_ID_CODE);
            return this;
        }

        public void modify(java.lang.String fieldName, java.lang.Object val) {
            switch (fieldName) {
                case "Code":
                    setCode((java.lang.String) val);
                    break;
                default:
                    throw new com.schemarise.alfa.runtime.AlfaRuntimeException(
                            schemarise.alfa.runtime.model.asserts.ConstraintType.UnknownField,
                            "Attempt to set unknown field " + fieldName);
            }
        }

        public Snippet build() {

            com.schemarise.alfa.runtime.utils.Utils.assertMandatoryFieldsSet(
                    builderConfig(),
                    __missingFields,
                    1,
                    schemarise.alfa.runtime.model.diff.Snippet.SnippetDescriptor.INSTANCE);

            Snippet obj;

            if (builderConfig().getCustomBuilderFactory().isPresent())
                obj =
                        (Snippet)
                                builderConfig()
                                        .getCustomBuilderFactory()
                                        .get()
                                        .create(builderConfig(), descriptor(), _code);
            else obj = new schemarise.alfa.runtime.model.diff.Snippet._SnippetConcrete(_code);

            if (builderConfig().shouldValidateOnBuild()) obj.validate(builderConfig());

            return obj;
        }

        private void clearMissingFlag(short flag) {

            __missingFields.clear(flag);
        }

        public java.lang.String toString() {
            return com.schemarise.alfa.runtime.utils.Utils.udtToString(
                    "schemarise.alfa.runtime.model.diff.Snippet",
                    new java.lang.String[] {"Code"},
                    new java.lang.Object[] {_code});
        }
    }
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Concrete class">

    final class _SnippetConcrete extends _Snippet__Base__ implements Snippet {

        private _SnippetConcrete() {
            super();
        }

        private _SnippetConcrete(java.lang.String _code) {
            super(_code);
        }
    }

    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Base class">
    abstract class _Snippet__Base__ {
        public java.lang.String _code;

        public _Snippet__Base__() {}

        public _Snippet__Base__(java.lang.String _code) {
            this._code = _code;
        }

        public java.lang.String getCode() {
            return _code;
        }

        public int hashCode() {
            return java.util.Objects.hash(_code);
        }

        public java.lang.String toString() {
            return com.schemarise.alfa.runtime.utils.Utils.udtToString(
                    "schemarise.alfa.runtime.model.diff.Snippet",
                    new java.lang.String[] {"Code"},
                    new java.lang.Object[] {_code});
        }

        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof schemarise.alfa.runtime.model.diff.Snippet._SnippetConcrete))
                return false;
            schemarise.alfa.runtime.model.diff.Snippet._SnippetConcrete rhs =
                    (schemarise.alfa.runtime.model.diff.Snippet._SnippetConcrete) o;
            return java.util.Objects.equals(_code, rhs._code);
        }

        public void traverse(com.schemarise.alfa.runtime.Visitor v) {}

        public java.util.Optional<? extends com.schemarise.alfa.runtime.Key> get$key() {
            return java.util.Optional.empty();
        }

        public com.schemarise.alfa.runtime.TypeDescriptor descriptor() {
            return schemarise.alfa.runtime.model.diff.Snippet.SnippetDescriptor.INSTANCE;
        }

        public Object get(java.lang.String fieldName) {
            switch (fieldName) {
                case "Code":
                    return _code;
                default:
                    throw new com.schemarise.alfa.runtime.AlfaRuntimeException(
                            "Cannot get unknown field " + fieldName);
            }
        }

        public void validate(com.schemarise.alfa.runtime.IBuilderConfig __builderConfig) {

            // TODO
            // _key if exists, will be mandatory
        }
    }

    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="TypeDescriptor class">

    public static final class SnippetDescriptor
            extends com.schemarise.alfa.runtime.utils.DefaultTypeDescriptor {
        public static java.lang.String TYPE_NAME = "schemarise.alfa.runtime.model.diff.Snippet";
        public static schemarise.alfa.runtime.model.diff.Snippet.SnippetDescriptor INSTANCE =
                new schemarise.alfa.runtime.model.diff.Snippet.SnippetDescriptor();

        private schemarise.alfa.runtime.model.UdtDataType _asUdtType_ =
                schemarise.alfa.runtime.model.UdtDataType.builder()
                        .setUdtType(schemarise.alfa.runtime.model.UdtMetaType.recordType)
                        .setFullyQualifiedName(TYPE_NAME)
                        .build();
        public static final short FIELD_ID_CODE = 0;
        public static final String FIELD_CODE = "Code";

        private schemarise.alfa.runtime.model.ScalarDataType _codeType =
                schemarise.alfa.runtime.model.ScalarDataType.builder()
                        .setScalarType(schemarise.alfa.runtime.model.ScalarType.stringType)
                        .build();

        /* -- Consumer string -- */
        java.util.function.Function<com.schemarise.alfa.runtime.DataSupplier, java.lang.String>
                _codeConsumerInner1 =
                        (supplierInner1) -> {
                            return supplierInner1.stringValue(
                                    ((schemarise.alfa.runtime.model.ScalarDataType) _codeType));
                        };
        java.util.function.BiConsumer<
                        schemarise.alfa.runtime.model.diff.Snippet._SnippetBuilderImpl,
                        com.schemarise.alfa.runtime.DataSupplier>
                _codeConsumer =
                        (builder, supplier) -> {
                            builder.setCode(_codeConsumerInner1.apply(supplier));
                        };

        /* -- Supplier string -- */
        java.util.function.BiConsumer<java.lang.String, com.schemarise.alfa.runtime.DataConsumer>
                _codeSupplierInner1 =
                        (pInner1, consumerInner1) -> {
                            consumerInner1.consume(
                                    ((schemarise.alfa.runtime.model.ScalarDataType) _codeType),
                                    pInner1);
                        };
        private java.util.function.BiConsumer<
                        schemarise.alfa.runtime.model.diff.Snippet,
                        com.schemarise.alfa.runtime.DataConsumer>
                _codeSupplier =
                        (p, consumer) -> {
                            _codeSupplierInner1.accept(p.getCode(), consumer);
                        };

        public java.util.Optional<
                        java.util.function.BiConsumer<
                                Snippet, com.schemarise.alfa.runtime.DataConsumer>>
                getFieldSupplier(java.lang.String fieldName) {
            return _fieldsMeta_.get(fieldName).getSupplier();
        }

        public java.util.Optional<
                        java.util.function.BiConsumer<
                                com.schemarise.alfa.runtime.Builder,
                                com.schemarise.alfa.runtime.DataSupplier>>
                getFieldConsumer(java.lang.String fieldName) {
            return _fieldsMeta_.get(fieldName).getConsumer();
        }

        public com.schemarise.alfa.runtime.FieldMeta codeMeta =
                new com.schemarise.alfa.runtime.FieldMeta(
                        java.util.Optional.of(_codeSupplier),
                        java.util.Optional.of(_codeConsumer),
                        java.util.Optional.of(_codeSupplierInner1),
                        java.util.Optional.of(_codeConsumerInner1),
                        _codeType,
                        FIELD_CODE,
                        java.util.Optional.empty());

        @Override
        public boolean hasBuilder() {
            return true;
        }

        @Override
        public boolean convertableToBuilder() {
            return true;
        }

        @Override
        public SnippetBuilder builder() {
            return new schemarise.alfa.runtime.model.diff.Snippet._SnippetBuilderImpl();
        }

        @Override
        public SnippetBuilder builder(com.schemarise.alfa.runtime.IBuilderConfig cc) {
            return new schemarise.alfa.runtime.model.diff.Snippet._SnippetBuilderImpl(cc);
        }

        public SnippetDescriptor() {
            super.init();
        }

        protected java.util.Map<java.lang.String, schemarise.alfa.runtime.model.Assert> _asserts_ =
                java.util.Collections.unmodifiableMap(
                        new java.util.LinkedHashMap() {
                            {
                            }
                        });

        protected java.util.Map<java.lang.String, com.schemarise.alfa.runtime.FieldMeta<Snippet>>
                _fieldsMeta_ =
                        java.util.Collections.unmodifiableMap(
                                new java.util.LinkedHashMap() {
                                    {
                                        put(FIELD_CODE, codeMeta);
                                    }
                                });

        @Override
        public schemarise.alfa.runtime.model.UdtDataType getUdtDataType() {
            return _asUdtType_;
        }

        @Override
        public java.util.Map<java.lang.String, schemarise.alfa.runtime.model.Assert> getAsserts() {
            return _asserts_;
        }

        @Override
        public java.util.Map<java.lang.String, com.schemarise.alfa.runtime.FieldMeta<Snippet>>
                getAllFieldsMeta() {
            return _fieldsMeta_;
        }

        @Override
        /** Not applicable - this is not an entity or a key directly linked to an entity */
        public java.util.Optional<com.schemarise.alfa.runtime.TypeDescriptor> getEntityKeyModel() {
            return java.util.Optional.empty();
        }

        @Override
        public java.lang.String fieldIdName(int id) {
            switch (id) {
                case FIELD_ID_CODE:
                    return FIELD_CODE;
                default:
                    throw new com.schemarise.alfa.runtime.AlfaRuntimeException(
                            "Unknown field id " + id);
            }
        }

        public boolean hasAbstractTypeFieldsInClosure() {
            return false;
        }

        public java.util.Set<java.lang.String> getImmediateDescendants() {
            return java.util.Collections.emptySet();
        }

        public java.util.Optional<
                        java.util.Map<java.lang.String, schemarise.alfa.runtime.model.Expression>>
                getAnnotations() {
            return java.util.Optional.empty();
        }

        public java.util.Set<schemarise.alfa.runtime.model.ModifierType> getModifiers() {
            return new java.util.HashSet<schemarise.alfa.runtime.model.ModifierType>() {
                {
                }
            };
        }

        public java.lang.String getChecksum() {
            /*
            schemarise.alfa.runtime.model.diff.Snippet{Code:string;}
            schemarise.alfa.runtime.model.diff.Snippet{Code:string;}
            */
            return "505d47e0:";
        }
    }
    // </editor-fold>

}
