name: Non-main CI Build

on:
  push:
    branches:
    - '!main'
    
jobs:
  ci_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build package
      run: mvn install
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAVEN_ARGS: -V -B --no-transfer-progress -DskipDistribution=true
